### ISSUE TITLE
Can provide the API to custom actions for different notifications.

### ISSUE THREAD

**Issue by archerx3** [CleverTap/CTNotificationContent#4]
```objec
- (void)didReceiveNotificationResponse:(UNNotificationResponse *)response
                     completionHandler:(void (^)(UNNotificationContentExtensionResponseOption))completion {
    UNNotificationContentExtensionResponseOption actionResponseOption = [self.contentViewController handleAction:response.actionIdentifier];
    completion(actionResponseOption);
}
```

```objec
- (UNNotificationContentExtensionResponseOption)handleAction:(NSString *)action
{
   // If can open some API, to handle custom action
}
```

We can custom more actions using code, the category is not "CTNotification".
But, can not handle the action event by ourself.

So, can provide?

**Comment by Aditi3** [comment]
Hey @archerx3 

Apologies for the delay.

True, you can't handle custom actions for CTNotificationContent, the library provides a class to accomplish default Image Slideshow view.

This is because when you use the Image Slider option provided by CleverTap, we need CTNotification category to enable transition between multiple images.

If you want to register your own actions which let you perform a function on a click, I recommend using CTNotificationService library that adds media attachments (image, gif, video, audio) to iOS push notifications.

Thanks!

**Comment by Aditi3** [comment]
Closing the issue, If you have more questions or concerns you can always reach out to the CleverTap support team at support@clevertap.com.
